sudo: required
cache:
  directories:
    - vendor

services:
  - docker
before_install:
  - docker pull cjy632258/php-fpm-slim
  - echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

script:
  - docker build -t cjy632258/storage .

after_success:
  - docker push cjy632258/storage